Aborts errand run if instance(s) are stopped
cloudfoundry/bosh pull request #2339
Opened 2021-11-17 21:00 UTC by lnguyen

A customer discovered a problem when running an errand on a VM that
was stopped with `bosh stop`. It is our understanding that Bosh will
never `stop` a VM automatically; this is a manual process that an
operator must perform.

Because we can't know why an operator stopped an instance that might
be used to run an errand, it's safer to just halt the planning process
and raise an error that informs the operator that manual intervention
is required.

We're not sure if this behavior is correct, thoughts?

2021-11-17 21:09 UTC, klakin-pivotal commented
So, a few things:
* You might be asking "When would you ever have multiple instances on which to run an errand?". We're not sure, but `instances` is an array, and writing the code to handle more than one instance was not notably more difficult than writing the code to handle one. We tested the relevant code by pre-populating the array with a value, and then stopping an instance.
* The nasty use of `unless` and the single line `if` statement are in there because `rubocop` wouldn't let us commit unless we used that style. IMO, it would be nice if we removed those `rubocop` rules, but this is just me complaining.

2021-11-18 10:54 UTC, beyhan commented
This look to me more related to the use case where an errand is running on an existing instance group (colocated). Have you tried this with an errand with a dedicated instance group? Here the VMs are usually stopped when the errand is finished.

2021-11-18 14:29 UTC, lnguyen commented
@beyhan yeah we tested it with the following
```
bosh run-errand hello --keep-alive
bosh stop hello
bosh run-errand hello # new code errors out
```

This was a bug reported by customer, the follow steps to reproduce
```
bosh run-errand hello --keep-alive
bosh stop hello
bosh run-errand hello # errand succeed and vm is deleted
bosh run-errand hello # vm is created but errand fails to run
```

2021-11-18 15:14 UTC, rkoster requested changes
Would it be possible to add at least a unit test for this?

2021-11-18 19:07 UTC, jpalermo approved these changes

2021-11-18 19:12 UTC, jpalermo approved these changes

2021-11-19 09:15 UTC, beyhan approved these changes

2021-11-19 15:27 UTC, rkoster approved these changes

2021-11-19 15:27 UTC, merged