Ruby 3.1.0
cloudfoundry/bosh pull request #2354
Opened 2022-01-28 10:11 UTC by ramonskie

this will bump the bosh director to use ruby 3.1
this is needed as ruby 3.1 supports openssl 3
which is now the default library used in `jammy(ubuntu 22.04)`

my only concern so far is that we will get a cascading effect by bumping the docker containers to use a new ruby version.
if the use the latest tag.

2022-02-02 11:00 UTC, beyhan requested changes
@ramonskie @bgandon why there is a `[WIP] bump ruby to 3.1.0` commit? Is this pr not ready for review yet?

2022-02-02 14:25 UTC, ramonskie commented
> @ramonskie @bgandon why there is a `[WIP] bump ruby to 3.1.0` commit? Is this pr not ready for review yet?

well it was the first commit when me and benjamin where pairing on it.
do you want me to squash this commit?

2022-02-03 09:09 UTC, beyhan commented
> well it was the first commit when me and benjamin where pairing on it. do you want me to squash this commit?

@ramonskie  please squash it. There are any way merge conflicts and the pr needs to be touched. Otherwise it looks good to me.

2022-02-04 12:35 UTC, rkoster approved these changes
Just a bunch of unrelated extensions changes, for the rest looks good to me

2022-02-04 12:35 UTC, rkoster commented on src/vendor/cache/extensions/x86_64-linux/3.1.0/eventmachine-abe347b824e3/gem_make.out
> +current directory: /home/ramonskie/workspace/bosh/bosh/src/vendor/cache/eventmachine-abe347b824e3/ext/fastfilereader
We should probably ignore the src/vendor/cache/extensions directory. Will create a separate PR for that.

2022-02-04 13:04 UTC, merged