Fix regression: Deployment manifests can contain yaml anchors
cloudfoundry/bosh pull request #2386
Opened 2022-06-21 14:28 UTC by mvach

### What is this change about?
Manifest do support yaml anchors again. That support got lost as regression of bosh version v272.1.0.

With Ruby 3.1 Psych was updated to version 4 which comes with an incompatible change. The incompatible change is that YAML.load is not an alias to unsave_load anymore but to save_load instead.

### Please provide contextual information.

The Issue for that PR is: https://github.com/cloudfoundry/bosh/issues/2385

### What tests have you run against this PR?

I have executed the director unittests and deployed it onto one of our landscapes. Then I deployed with that fixed BOSH version a manifest that uses aliases.

### How should this change be described in bosh release notes?

Deployment manifests do support yaml anchors again.

### Does this PR introduce a breaking change?

Actually it fixes a breaking change

### Tag your pair, your PM, and/or team!
@fmoehler

2022-06-23 14:52 UTC, rkoster requested changes
Please add unit tests for this

2022-06-27 13:01 UTC, mvach commented
Hi @rkoster,
I added a unit test to update_deployment_spec.rb. This is of course not covering all the touched YAML.loads. Do you want me to test them one by one or is that single one already enough from your perspective? Testing them now one by one could become relatively expensive.

2022-06-29 13:27 UTC, ramonskie approved these changes
LGTM

2022-06-30 15:19 UTC, rkoster approved these changes

2022-06-30 15:20 UTC, rkoster commented
Thanks! @mvach

2022-06-30 15:20 UTC, merged