auto bump the azure storage cli
cloudfoundry/bosh pull request #2455
Opened 2023-07-18 13:19 UTC by fmoehler

### What is this change about?

We introduce automatic bumping for the azure storage cli

### Please provide contextual information.

As the azure-storage-cli is now being bumped automatically, we also want to do it within bosh

### What tests have you run against this PR?

Because we don't have enough permissions in the cloudfoundry org, we could not test this so far

### How should this change be described in bosh release notes?

Introduce auto bumping for azure-storage-cli

### Does this PR introduce a breaking change?

No

### Tag your pair, your PM, and/or team!

2023-07-19 12:42 UTC, lnguyen approved these changes
LGTM

2023-07-20 06:51 UTC, mvach commented on ci/pipeline.yml
> +      file: bosh-src/ci/tasks/bump-blobstore-cli.yml
I noticed that `bosh-src/ci/tasks/bump-blobstore-cli.sh` is checking the blobstore type.

The configured `BLOBSTORE_TYPE: azure-storage` would result in `"Error: unknown BLOBSTORE_TYPE='${BLOBSTORE_TYPE}'; exiting"`

Don't we need to update `bosh-src/ci/tasks/bump-blobstore-cli.sh` first?

2023-07-20 06:52 UTC, mvach requested changes
lgtm

2023-07-20 07:32 UTC, mvach approved these changes

2023-07-20 14:12 UTC, rkoster approved these changes

2023-07-20 14:43 UTC, rkoster commented
This PR is blocked on further director changes which actually use the azure cli

2023-08-04 09:09 UTC, beyhan commented
We have enough reviews and https://github.com/cloudfoundry/bosh/pull/2456 got approved and merged. That is why I will merge this one also.

2023-08-04 09:09 UTC, merged